// ignore_for_file: prefer_const_constructors

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'loading_skeleton.dart';

class UsersRolesPage extends StatefulWidget {
  const UsersRolesPage({super.key, required this.searchQuery});

  final ValueListenable<String> searchQuery;

  @override
  State<UsersRolesPage> createState() => _UsersRolesPageState();
}

class _UsersRolesPageState extends State<UsersRolesPage> {
  static const roles = ['admin', 'chef', 'cashier', 'waiter', 'delivery rider'];
  static const protectedRoleUid = 'J5GKrWrL7pSq0tWADtOUx18r6Al2';

  String _normalizeRole(String? role) {
    final value = (role ?? '').trim().toLowerCase();
    if (value == 'delivery_rider') {
      return 'delivery rider';
    }
    return value;
  }

  Future<void> _writeAudit({
    required String action,
    required String target,
    required String details,
  }) async {
    await FirebaseFirestore.instance.collection('audit_logs').add({
      'action': action,
      'target': target,
      'details': details,
      'by': FirebaseAuth.instance.currentUser?.email ?? 'unknown',
      'timestamp': FieldValue.serverTimestamp(),
    });
  }

  Future<void> _updateRole(
    QueryDocumentSnapshot<Map<String, dynamic>> doc,
    String role,
  ) async {
    if (doc.id == protectedRoleUid) {
      if (!mounted) {
        return;
      }
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Role is locked for this UID')),
      );
      return;
    }
    await doc.reference.set({
      'role': role,
      'updatedAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
    await _writeAudit(
      action: 'role_changed',
      target: doc.id,
      details: 'Role changed to $role',
    );
    if (!mounted) {
      return;
    }
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('Updated role to $role')),
    );
  }

  Future<void> _createUser() async {
    final generatedUid =
        FirebaseFirestore.instance.collection('users').doc().id;
    final uidController = TextEditingController(text: generatedUid);
    final nameController = TextEditingController();
    final emailController = TextEditingController();
    final phoneController = TextEditingController();
    String role = 'waiter';

    final shouldSave = await showDialog<bool>(
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              title: const Text('Create User'),
              content: SizedBox(
                width: 460,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    TextField(
                      controller: uidController,
                      decoration: const InputDecoration(
                        labelText: 'UID (auto-generated by default)',
                      ),
                    ),
                    const SizedBox(height: 10),
                    TextField(
                      controller: nameController,
                      decoration: const InputDecoration(labelText: 'Name'),
                    ),
                    const SizedBox(height: 10),
                    TextField(
                      controller: emailController,
                      decoration: const InputDecoration(labelText: 'Email'),
                    ),
                    const SizedBox(height: 10),
                    TextField(
                      controller: phoneController,
                      decoration: const InputDecoration(labelText: 'Phone'),
                    ),
                    const SizedBox(height: 10),
                    DropdownButtonFormField<String>(
                      initialValue: role,
                      items: roles
                          .map(
                            (value) => DropdownMenuItem(
                              value: value,
                              child: Text(value),
                            ),
                          )
                          .toList(),
                      decoration: const InputDecoration(labelText: 'Role'),
                      onChanged: (value) {
                        if (value == null) {
                          return;
                        }
                        setDialogState(() => role = value);
                      },
                    ),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.pop(context, false),
                  child: const Text('Cancel'),
                ),
                FilledButton(
                  onPressed: () => Navigator.pop(context, true),
                  child: const Text('Create'),
                ),
              ],
            );
          },
        );
      },
    );

    if (shouldSave != true) {
      uidController.dispose();
      nameController.dispose();
      emailController.dispose();
      phoneController.dispose();
      return;
    }

    final uidInput = uidController.text.trim();
    final uid = uidInput.isEmpty ? generatedUid : uidInput;

    await FirebaseFirestore.instance.collection('users').doc(uid).set({
      'name': nameController.text.trim(),
      'email': emailController.text.trim(),
      'phone': phoneController.text.trim(),
      'role': role,
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
    await _writeAudit(
      action: 'user_created',
      target: uid,
      details: 'Created user with role $role',
    );

    uidController.dispose();
    nameController.dispose();
    emailController.dispose();
    phoneController.dispose();
    if (!mounted) {
      return;
    }
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(SnackBar(content: Text('User created: $uid')));
  }

  Future<void> _editUser(
      QueryDocumentSnapshot<Map<String, dynamic>> doc) async {
    final data = doc.data();
    final roleLocked = doc.id == protectedRoleUid;
    final nameController = TextEditingController(
      text: data['name']?.toString() ?? '',
    );
    final emailController = TextEditingController(
      text: data['email']?.toString() ?? '',
    );
    final phoneController = TextEditingController(
      text: data['phone']?.toString() ?? '',
    );
    String role = data['role']?.toString().toLowerCase() ?? 'waiter';
    if (!roles.contains(role)) {
      role = 'waiter';
    }

    final shouldSave = await showDialog<bool>(
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              title: Text('Edit User'),
              content: SizedBox(
                width: 460,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    TextField(
                      controller: nameController,
                      decoration: const InputDecoration(labelText: 'Name'),
                    ),
                    const SizedBox(height: 10),
                    TextField(
                      controller: emailController,
                      decoration: const InputDecoration(labelText: 'Email'),
                    ),
                    const SizedBox(height: 10),
                    TextField(
                      controller: phoneController,
                      decoration: const InputDecoration(labelText: 'Phone'),
                    ),
                    const SizedBox(height: 10),
                    DropdownButtonFormField<String>(
                      initialValue: role,
                      items: roles
                          .map(
                            (value) => DropdownMenuItem(
                              value: value,
                              child: Text(value),
                            ),
                          )
                          .toList(),
                      decoration: const InputDecoration(labelText: 'Role'),
                      onChanged: roleLocked
                          ? null
                          : (value) {
                              if (value == null) {
                                return;
                              }
                              setDialogState(() => role = value);
                            },
                    ),
                    if (roleLocked)
                      const Padding(
                        padding: EdgeInsets.only(top: 8),
                        child: Align(
                          alignment: Alignment.centerLeft,
                          child: Text(
                            'Role is locked for this UID.',
                            style: TextStyle(fontSize: 12),
                          ),
                        ),
                      ),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.pop(context, false),
                  child: const Text('Cancel'),
                ),
                FilledButton(
                  onPressed: () => Navigator.pop(context, true),
                  child: const Text('Save'),
                ),
              ],
            );
          },
        );
      },
    );

    if (shouldSave != true) {
      nameController.dispose();
      emailController.dispose();
      phoneController.dispose();
      return;
    }

    final roleToSave =
        roleLocked ? _normalizeRole(data['role']?.toString()) : role;
    await doc.reference.set({
      'name': nameController.text.trim(),
      'email': emailController.text.trim(),
      'phone': phoneController.text.trim(),
      'role': roleToSave,
      'updatedAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
    await _writeAudit(
      action: 'user_updated',
      target: doc.id,
      details: 'Updated user profile and role to $roleToSave',
    );

    nameController.dispose();
    emailController.dispose();
    phoneController.dispose();
    if (!mounted) {
      return;
    }
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(const SnackBar(content: Text('User updated')));
  }

  Future<void> _deleteUser(
      QueryDocumentSnapshot<Map<String, dynamic>> doc) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Delete user?'),
          content: Text('Delete user document "${doc.id}"?'),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context, false),
              child: const Text('Cancel'),
            ),
            FilledButton(
              onPressed: () => Navigator.pop(context, true),
              style: FilledButton.styleFrom(
                backgroundColor: Colors.red,
                foregroundColor: Colors.white,
              ),
              child: const Text('Delete'),
            ),
          ],
        );
      },
    );
    if (confirmed != true) {
      return;
    }
    await doc.reference.delete();
    await _writeAudit(
      action: 'user_deleted',
      target: doc.id,
      details: 'Deleted user document',
    );
    if (!mounted) {
      return;
    }
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(const SnackBar(content: Text('User deleted')));
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
      stream: FirebaseFirestore.instance.collection('users').snapshots(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const _UsersSkeleton();
        }
        if (snapshot.hasError) {
          return FirestoreErrorPanel(
            title: 'Users and roles cannot be loaded.',
            error: snapshot.error,
          );
        }
        final docs = snapshot.data?.docs ?? [];
        return ValueListenableBuilder<String>(
          valueListenable: widget.searchQuery,
          builder: (context, query, _) {
            final normalizedQuery = query.trim().toLowerCase();
            final filtered = docs.where((doc) {
              if (normalizedQuery.isEmpty) {
                return true;
              }
              final data = doc.data();
              final pool = [
                data['name']?.toString() ?? '',
                data['email']?.toString() ?? '',
                data['phone']?.toString() ?? '',
                data['role']?.toString() ?? '',
              ].join(' ').toLowerCase();
              return pool.contains(normalizedQuery);
            }).toList();

            final roleCounts = <String, int>{for (final role in roles) role: 0};
            for (final doc in docs) {
              final role = _normalizeRole(doc.data()['role']?.toString());
              if (roleCounts.containsKey(role)) {
                roleCounts[role] = roleCounts[role]! + 1;
              }
            }

            return Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                children: [
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(18),
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        colors: [
                          Theme.of(context).colorScheme.primary,
                          Theme.of(context)
                              .colorScheme
                              .primary
                              .withValues(alpha: 0.82),
                        ],
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                      ),
                      borderRadius: BorderRadius.circular(18),
                    ),
                    child: Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'User & Role Management',
                                style: Theme.of(context)
                                    .textTheme
                                    .headlineSmall
                                    ?.copyWith(color: Colors.white),
                              ),
                              const SizedBox(height: 4),
                              Text(
                                'Manage staff identities, role access and user records.',
                                style: Theme.of(context)
                                    .textTheme
                                    .bodySmall
                                    ?.copyWith(color: Colors.white70),
                              ),
                            ],
                          ),
                        ),
                        FilledButton.icon(
                          onPressed: _createUser,
                          style: FilledButton.styleFrom(
                            backgroundColor: Colors.white,
                            foregroundColor:
                                Theme.of(context).colorScheme.primary,
                          ),
                          icon: const Icon(Icons.person_add_alt_1),
                          label: const Text('Add User'),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 12),
                  Wrap(
                    spacing: 10,
                    runSpacing: 10,
                    children: [
                      _InfoCard(label: 'Users', value: docs.length.toString()),
                      ...roleCounts.entries.map(
                        (entry) => _InfoCard(
                          label: entry.key,
                          value: entry.value.toString(),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  Expanded(
                    child: filtered.isEmpty
                        ? const Center(child: Text('No users found.'))
                        : GridView.builder(
                            gridDelegate:
                                const SliverGridDelegateWithMaxCrossAxisExtent(
                              maxCrossAxisExtent: 520,
                              mainAxisSpacing: 12,
                              crossAxisSpacing: 12,
                              childAspectRatio: 1.55,
                            ),
                            itemCount: filtered.length,
                            itemBuilder: (context, index) {
                              final doc = filtered[index];
                              final data = doc.data();
                              final name = data['name']?.toString().trim();
                              final email = data['email']?.toString().trim();
                              final phone = data['phone']?.toString().trim();
                              final role = _normalizeRole(
                                data['role']?.toString(),
                              );
                              final roleLocked = doc.id == protectedRoleUid;
                              return Card(
                                child: Padding(
                                  padding: const EdgeInsets.all(14),
                                  child: Column(
                                    children: [
                                      Row(
                                        children: [
                                          CircleAvatar(
                                            child: Text(
                                              (name?.isNotEmpty == true
                                                      ? name![0]
                                                      : 'U')
                                                  .toUpperCase(),
                                            ),
                                          ),
                                          const SizedBox(width: 12),
                                          Expanded(
                                            child: Column(
                                              crossAxisAlignment:
                                                  CrossAxisAlignment.start,
                                              children: [
                                                Text(
                                                  name?.isEmpty ?? true
                                                      ? 'Unnamed User'
                                                      : name!,
                                                  style: Theme.of(context)
                                                      .textTheme
                                                      .titleSmall
                                                      ?.copyWith(
                                                        fontWeight:
                                                            FontWeight.w700,
                                                      ),
                                                ),
                                                Text(
                                                  email?.isEmpty ?? true
                                                      ? 'No email'
                                                      : email!,
                                                  style: Theme.of(context)
                                                      .textTheme
                                                      .bodySmall,
                                                ),
                                              ],
                                            ),
                                          ),
                                          if (roleLocked)
                                            Container(
                                              padding:
                                                  const EdgeInsets.symmetric(
                                                horizontal: 10,
                                                vertical: 6,
                                              ),
                                              decoration: BoxDecoration(
                                                color: Colors.amber
                                                    .withValues(alpha: 0.16),
                                                borderRadius:
                                                    BorderRadius.circular(14),
                                              ),
                                              child: const Row(
                                                mainAxisSize: MainAxisSize.min,
                                                children: [
                                                  Icon(Icons.lock_outline,
                                                      size: 14),
                                                  SizedBox(width: 6),
                                                  Text('Role Locked'),
                                                ],
                                              ),
                                            ),
                                        ],
                                      ),
                                      const SizedBox(height: 12),
                                      _UserMeta(
                                        label: 'Phone',
                                        value: phone?.isEmpty ?? true
                                            ? 'No phone'
                                            : phone!,
                                      ),
                                      const SizedBox(height: 10),
                                      Wrap(
                                        spacing: 8,
                                        runSpacing: 8,
                                        crossAxisAlignment:
                                            WrapCrossAlignment.center,
                                        children: [
                                          SizedBox(
                                            width: 180,
                                            child:
                                                DropdownButtonFormField<String>(
                                              initialValue: roles.contains(role)
                                                  ? role
                                                  : 'waiter',
                                              decoration: const InputDecoration(
                                                labelText: 'Role',
                                              ),
                                              items: roles
                                                  .map(
                                                    (value) => DropdownMenuItem(
                                                      value: value,
                                                      child: Text(value),
                                                    ),
                                                  )
                                                  .toList(),
                                              onChanged: roleLocked
                                                  ? null
                                                  : (value) async {
                                                      if (value == null ||
                                                          value == role) {
                                                        return;
                                                      }
                                                      await _updateRole(
                                                          doc, value);
                                                    },
                                            ),
                                          ),
                                          OutlinedButton.icon(
                                            onPressed: () => _editUser(doc),
                                            icon:
                                                const Icon(Icons.edit_outlined),
                                            label: const Text('Edit'),
                                          ),
                                          const SizedBox(width: 8),
                                          OutlinedButton.icon(
                                            onPressed: () => _deleteUser(doc),
                                            icon: const Icon(
                                              Icons.delete_outline,
                                            ),
                                            label: const Text('Delete'),
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                              );
                            },
                          ),
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }
}

class _InfoCard extends StatelessWidget {
  const _InfoCard({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 130,
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.black12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            style: Theme.of(context).textTheme.labelSmall,
          ),
          const SizedBox(height: 3),
          Text(
            value,
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.w700,
                ),
          ),
        ],
      ),
    );
  }
}

class _UserMeta extends StatelessWidget {
  const _UserMeta({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
      decoration: BoxDecoration(
        color: Colors.black.withValues(alpha: 0.03),
        borderRadius: BorderRadius.circular(10),
      ),
      child: RichText(
        text: TextSpan(
          style: Theme.of(context).textTheme.bodySmall?.copyWith(
                color: Theme.of(context).colorScheme.onSurface,
              ),
          children: [
            TextSpan(
              text: '$label: ',
              style: const TextStyle(fontWeight: FontWeight.w700),
            ),
            TextSpan(text: value),
          ],
        ),
      ),
    );
  }
}

class _UsersSkeleton extends StatelessWidget {
  const _UsersSkeleton();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.all(20),
      child: Column(
        children: [
          SkeletonBox(height: 32),
          SizedBox(height: 12),
          SkeletonBox(height: 90),
          SizedBox(height: 10),
          SkeletonBox(height: 90),
          SizedBox(height: 10),
          SkeletonBox(height: 90),
        ],
      ),
    );
  }
}
